import { L, type AppStatus, type LText } from "./types";

/** UI chrome copy. Service content comes from the spec, this is everything else. */
export const S = {
  appName: L("Queueless Bhopal", "क्यूलेस भोपाल"),
  tagline: L(
    "Find a government service, follow the steps, skip the line.",
    "सरकारी सेवा खोजें, चरणों का पालन करें, लाइन से बचें।",
  ),
  demoBanner: L(
    "Demo build — reference numbers, queues and statuses are simulated.",
    "डेमो संस्करण — संदर्भ संख्या, कतार और स्थिति नकली हैं।",
  ),

  // nav
  home: L("Home", "होम"),
  tutorials: L("Form Tutorials", "फॉर्म ट्यूटोरियल"),
  dashboard: L("My Dashboard", "मेरा डैशबोर्ड"),
  staff: L("Staff", "स्टाफ"),
  admin: L("Admin", "एडमिन"),
  applications: L("Applications", "आवेदन"),

  // tutorials
  tutorialHub: L("Form Filling Visual Tutorials", "फॉर्म भरने के विजुअल ट्यूटोरियल"),
  tutorialTagline: L(
    "Interactive screenshot walkthroughs and field-by-field guidelines so you never make mistakes or face rejection.",
    "इंटरैक्टिव स्क्रीनशॉट वॉकथ्रू और फ़ील्ड-दर-फ़ील्ड गाइड ताकि आपसे कोई गलती न हो और फॉर्म अस्वीकृत न हो।",
  ),
  fieldInspector: L("Field Inspector", "फ़ील्ड विवरण"),
  whatToEnter: L("What to enter here", "यहाँ क्या भरना है"),
  sampleValue: L("Sample valid format", "मान्य प्रारूप उदाहरण"),
  commonTrap: L("Common rejection trap", "अस्वीकृति का मुख्य कारण"),
  proTip: L("Pro Tip", "विशेष सलाह"),
  clickToInspect: L(
    "Click any numbered hotspot pin on the screenshot below to view exact instructions for that field.",
    "उस फ़ील्ड के सटीक निर्देश देखने के लिए नीचे दिए गए स्क्रीनशॉट पर किसी भी क्रमांकित पिन पर क्लिक करें।",
  ),
  practiceMode: L("Practice Simulator", "प्रैक्टिस सिम्युलेटर"),
  interactiveTour: L("Screenshot Walkthrough", "स्क्रीनशॉट वॉकथ्रू"),
  docPrep: L("Document Prep & Scanner Guide", "दस्तावेज़ गाइड"),
  testYourInputs: L(
    "Practice filling this form safely with live validation before applying on the official portal.",
    "आधिकारिक पोर्टल पर जाने से पहले लाइव जाँच के साथ इस फॉर्म को भरने का सुरक्षित अभ्यास करें।",
  ),
  allTutorials: L("All Tutorials", "सभी ट्यूटोरियल"),
  exploreTutorials: L("Explore All Tutorials", "सभी ट्यूटोरियल देखें"),
  rejectionPrevention: L("Top Rejection Traps & Solutions", "फॉर्म रिजेक्ट होने के कारण और समाधान"),
  prerequisites: L("Keep these ready before starting", "शुरू करने से पहले इन्हें तैयार रखें"),
  officialPortal: L("Official Portal", "आधिकारिक पोर्टल"),
  openOfficialPortal: L("Open Official Portal", "आधिकारिक पोर्टल खोलें"),
  estimatedTime: L("Estimated time", "अनुमानित समय"),
  difficulty: L("Difficulty", "कठिनाई स्तर"),
  easy: L("Easy", "सरल"),
  medium: L("Moderate", "मध्यम"),
  hard: L("Requires Verification", "सत्यापन आवश्यक"),
  allSteps: L("All steps", "सभी चरण"),
  viewTutorial: L("View Interactive Tutorial", "इंटरैक्टिव ट्यूटोरियल देखें"),
  tutorialBadge: L("Interactive Visual Guide", "इंटरैक्टिव विजुअल गाइड"),
  filterByCategory: L("Filter by category", "श्रेणी अनुसार फ़िल्टर करें"),
  allCategories: L("All categories", "सभी श्रेणियाँ"),
  activeHotspot: L("Selected Field", "चयनित फ़ील्ड"),
  trySimulator: L("Try Practice Simulator", "प्रैक्टिस सिम्युलेटर आज़माएँ"),
  simulateSubmit: L("Validate Form Inputs", "फॉर्म विवरण सत्यापित करें"),
  validationSuccess: L("All fields validated! You are ready to fill the official form.", "सभी फ़ील्ड सही हैं! आप आधिकारिक फॉर्म भरने के लिए तैयार हैं।"),
  validationError: L("Please correct the highlighted fields according to the official rules.", "कृपया नियमों के अनुसार चिन्हित फ़ील्ड्स को ठीक करें।"),
  compressDocsHint: L("Government portals strictly reject files over 200 KB. Keep PDF scans clean and sharp.", "सरकारी पोर्टल 200 KB से बड़ी फ़ाइलों को अस्वीकार कर देते हैं। PDF साफ़ और स्पष्ट रखें।"),
  zoomScreenshot: L("Enlarge Screenshot", "स्क्रीनशॉट बड़ा करें"),


  // search / home
  searchPlaceholder: L("Search a service, e.g. domicile", "सेवा खोजें, जैसे मूल निवासी"),
  search: L("Search", "खोजें"),
  browseByDept: L("Browse by department", "विभाग अनुसार देखें"),
  allDepartments: L("All departments", "सभी विभाग"),
  popular: L("Popular services", "लोकप्रिय सेवाएँ"),
  noResults: L("No services matched.", "कोई सेवा नहीं मिली।"),
  resultsCount: L("services", "सेवाएँ"),

  // service detail
  eligibility: L("Who can apply", "कौन आवेदन कर सकता है"),
  fee: L("Fee", "शुल्क"),
  processingTime: L("Processing time", "प्रक्रिया समय"),
  requirements: L("Documents you need", "आवश्यक दस्तावेज़"),
  required: L("Required", "अनिवार्य"),
  optional: L("Optional", "वैकल्पिक"),
  officialSources: L("Official sources", "आधिकारिक स्रोत"),
  accessedOn: L("checked on", "जाँच की गई"),
  onlineAvailable: L("Available online", "ऑनलाइन उपलब्ध"),
  physicalVisit: L("Office visit required", "कार्यालय जाना आवश्यक"),
  openGuide: L("Open step-by-step guide", "चरण-दर-चरण गाइड खोलें"),
  startApplication: L("Start demo application", "डेमो आवेदन शुरू करें"),
  joinQueueCta: L("Join virtual queue", "वर्चुअल कतार में जुड़ें"),
  saveService: L("Save", "सहेजें"),
  saved: L("Saved", "सहेजा गया"),
  commonMistakes: L("Common mistakes", "आम गलतियाँ"),
  faqs: L("Questions people ask", "अक्सर पूछे जाने वाले प्रश्न"),
  backToService: L("Back to service", "सेवा पर वापस"),

  // guide
  guide: L("Step-by-step guide", "चरण-दर-चरण गाइड"),
  stepOf: L("Step", "चरण"),
  of: L("of", "में से"),
  next: L("Next", "आगे"),
  previous: L("Back", "पीछे"),
  finishGuide: L("I've finished", "मैंने पूरा किया"),
  tip: L("Tip", "सुझाव"),
  stuck: L("I'm stuck", "मैं अटक गया हूँ"),
  stuckHelp: L("Ask for help with this step", "इस चरण में मदद पूछें"),
  askAssistant: L("Ask", "पूछें"),
  officialScreenshot: L("Official screenshot", "आधिकारिक स्क्रीनशॉट"),
  simulatedVisual: L("Simulated illustration", "नकली चित्र"),

  // applications
  tracker: L("Application tracker", "आवेदन ट्रैकर"),
  applicantName: L("Applicant name", "आवेदक का नाम"),
  submit: L("Submit", "जमा करें"),
  submitted: L("Submitted", "जमा किया गया"),
  refNo: L("Reference no.", "संदर्भ संख्या"),
  simulatedRef: L("Simulated reference — not a real government number.", "नकली संदर्भ — यह वास्तविक सरकारी संख्या नहीं है।"),
  status: L("Status", "स्थिति"),
  timeline: L("Progress", "प्रगति"),
  noApplications: L("No applications yet.", "अभी कोई आवेदन नहीं।"),
  advanceDemo: L("Advance demo status", "डेमो स्थिति आगे बढ़ाएँ"),
  viewDetails: L("View", "देखें"),

  // status labels
  st_submitted: L("Submitted", "जमा किया गया"),
  st_document_check: L("Document check", "दस्तावेज़ जाँच"),
  st_field_verification: L("Field verification", "क्षेत्र सत्यापन"),
  st_approved: L("Approved", "स्वीकृत"),
  st_rejected: L("Rejected", "अस्वीकृत"),

  // queue
  queue: L("Virtual queue", "वर्चुअल कतार"),
  joinQueue: L("Join queue", "कतार में जुड़ें"),
  yourName: L("Your name", "आपका नाम"),
  yourToken: L("Your token", "आपका टोकन"),
  nowServing: L("Now serving", "अब सेवा में"),
  peopleAhead: L("people ahead of you", "आपसे आगे लोग"),
  estWait: L("Estimated wait", "अनुमानित प्रतीक्षा"),
  avgService: L("Rolling average per person", "प्रति व्यक्ति औसत"),
  minutes: L("min", "मिनट"),
  approaching: L("Almost your turn — head to the counter now.", "आपकी बारी करीब है — काउंटर पर पहुँचें।"),
  yourTurn: L("It's your turn. Go to the counter.", "आपकी बारी है। काउंटर पर जाएँ।"),
  tokenDone: L("Visit complete.", "मुलाक़ात पूरी हुई।"),
  tokenSkipped: L("Token skipped — rejoin the queue.", "टोकन छोड़ा गया — फिर से कतार में जुड़ें।"),
  leaveQueue: L("Leave queue", "कतार छोड़ें"),
  waiting: L("Waiting", "प्रतीक्षा में"),
  queueClosed: L("Counter closed", "काउंटर बंद"),
  location: L("Location", "स्थान"),

  // dashboard
  activeToken: L("Active token", "सक्रिय टोकन"),
  savedServices: L("Saved services", "सहेजी गई सेवाएँ"),
  pendingDocs: L("Documents still to gather", "जुटाने बाकी दस्तावेज़"),
  nothingHere: L("Nothing here yet.", "अभी कुछ नहीं।"),
  demoLogin: L("Demo sign-in", "डेमो साइन-इन"),
  signedInAs: L("Signed in as", "साइन इन:"),

  // staff
  staffDashboard: L("Counter dashboard", "काउंटर डैशबोर्ड"),
  callNext: L("Call next", "अगला बुलाएँ"),
  complete: L("Complete", "पूरा करें"),
  skip: L("Skip", "छोड़ें"),
  pauseCounter: L("Pause counter", "काउंटर रोकें"),
  resumeCounter: L("Resume counter", "काउंटर चालू करें"),
  resetQueue: L("Reset demo queue", "डेमो कतार रीसेट करें"),
  resetConfirm: L("Clear all tokens in this queue?", "इस कतार के सभी टोकन हटाएँ?"),
  resetAll: L("Reset whole demo", "पूरा डेमो रीसेट करें"),
  resetAllConfirm: L(
    "Reset the whole demo — queues, applications and admin state?",
    "पूरा डेमो रीसेट करें — कतार, आवेदन और एडमिन स्थिति?",
  ),
  liveQueue: L("Live queue", "लाइव कतार"),
  emptyQueue: L("Queue is empty.", "कतार खाली है।"),
  selectQueue: L("Counter", "काउंटर"),

  // admin
  serviceOps: L("Service operations", "सेवा संचालन"),
  compile: L("Run compiler", "कंपाइलर चलाएँ"),
  compiling: L("Compiling…", "कंपाइल हो रहा है…"),
  draftSpec: L("Draft spec", "ड्राफ्ट स्पेक"),
  runVerification: L("Run verification", "सत्यापन चलाएँ"),
  verifying: L("Verifying…", "सत्यापन हो रहा है…"),
  healthReport: L("Health report", "हेल्थ रिपोर्ट"),
  history: L("Verification history", "सत्यापन इतिहास"),
  publish: L("Publish", "प्रकाशित करें"),
  published: L("Published", "प्रकाशित"),
  publishBlocked: L("Resolve blockers before publishing.", "प्रकाशन से पहले ब्लॉकर हल करें।"),
  flag: L("Flag an issue", "समस्या दर्ज करें"),
  flagged: L("Flag recorded.", "समस्या दर्ज हो गई।"),
  noReport: L("No verification run yet.", "अभी सत्यापन नहीं हुआ।"),
  verdict: L("Verdict", "निर्णय"),
};

export const APP_STATUS_LABEL: Record<AppStatus, LText> = {
  submitted: S.st_submitted,
  document_check: S.st_document_check,
  field_verification: S.st_field_verification,
  approved: S.st_approved,
  rejected: S.st_rejected,
};
